// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";

import { Providers } from "@/components/layout/Providers";
import "./globals.css";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import { auth } from "@/auth";
import { IAuthSessionUser } from "@/lib/types/types";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body>
        <Providers authUser={session?.user as IAuthSessionUser}>
          {children}
        </Providers>
      </body>
    </html>
  );
}
